import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { createServer } from '../server.js';
import { filterSavedItems, matchesSavedItem } from '../public/search.js';
import { inheritedPhotoNames, nextPhotoNumber, photoFilename, photoSize, validPhoto } from '../public/photos.js';

function request(port, path='/') { return new Promise((resolve,reject)=>{const req=http.get({hostname:'127.0.0.1',port,path},res=>{let body='';res.on('data',x=>body+=x);res.on('end',()=>resolve({status:res.statusCode,body,headers:res.headers}))});req.on('error',reject)}) }

test('serves the iPhone app and health check',async()=>{const server=createServer();await new Promise(ok=>server.listen(0,'127.0.0.1',ok));try{const port=server.address().port,home=await request(port),health=await request(port,'/health');assert.equal(home.status,200);assert.match(home.body,/Private working copies/);assert.deepEqual(JSON.parse(health.body),{ok:true,version:12})}finally{await new Promise(ok=>server.close(ok))}});
test('has distinct idea, task, and voice capture',async()=>{const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8');assert.match(html,/New Idea/);assert.match(html,/New Task/);assert.match(html,/Voice Memo/);assert.match(html,/voiceCount/);assert.match(html,/Home/)});
test('stores locally, supports rename, and exports through the share sheet',async()=>{const js=await readFile(new URL('../public/app.js',import.meta.url),'utf8'),html=await readFile(new URL('../public/index.html',import.meta.url),'utf8');assert.match(js,/localStorage/);assert.match(js,/indexedDB/);assert.match(js,/navigator\.share/);assert.match(js,/renamedFile/);assert.match(js,/saveVoiceName/);assert.match(html,/Save\/Rename Voice Memo/);assert.doesNotMatch(js,/\/local\//)});
test('autosaves visible edits and exports the current copy',async()=>{const js=await readFile(new URL('../public/app.js',import.meta.url),'utf8'),html=await readFile(new URL('../public/index.html',import.meta.url),'utf8');assert.match(js,/function markDirty/);assert.match(js,/setTimeout\(\(\)=>saveNote\(true\),700\)/);assert.match(js,/function exportNote\(\)\{saveNote\(true\)/);assert.match(html,/Export Current Copy/);assert.doesNotMatch(html,/Draft protected/)});
test('voice memos append related recordings without overwriting',async()=>{const js=await readFile(new URL('../public/app.js',import.meta.url),'utf8'),html=await readFile(new URL('../public/index.html',import.meta.url),'utf8');assert.match(js,/recordings\.push/);assert.match(js,/Add Related Recording/);assert.match(js,/Part-/);assert.match(js,/migrateVoice/);assert.match(html,/voicePreview.*recordBtn/s);assert.doesNotMatch(js,/Record Again/)});
test('related recording action follows the recording cards without helper clutter',async()=>{const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8'),js=await readFile(new URL('../public/app.js',import.meta.url),'utf8');assert.match(html,/voicePreview.*recordBtn.*deleteVoiceThread/s);assert.doesNotMatch(html,/Enter a name before recording/);assert.doesNotMatch(js,/never replaces the recordings above/)});
test('search matches title, filename, text, and type with normalization and AND terms',()=>{const idea={type:'IDEA',title:'Noise Cancelling App',filename:'[Idea-noise] 26-Sep-14-01.md',text:'Public bathroom concept'};assert.equal(matchesSavedItem(idea,'NOISE'),true);assert.equal(matchesSavedItem(idea,'26-sep-14'),true);assert.equal(matchesSavedItem(idea,'bathroom'),true);assert.equal(matchesSavedItem(idea,'idea'),true);assert.equal(matchesSavedItem(idea,'  NOISE bathroom  '),true);assert.equal(matchesSavedItem(idea,'noise missing'),false);assert.equal(matchesSavedItem(idea,'   '),true);assert.equal(matchesSavedItem({type:'VOICE',title:'Anata Wa',filename:'[Voice-Anata-Wa] 26-Sep-14-01-Part-01.m4a'},'voice anata'),true)});
test('search combines with every category filter, preserves order, and does not mutate items',()=>{const items=[{id:'new',type:'TASK',title:'Meeting task',filename:'task-new.md',text:'Supplier call'},{id:'middle',type:'IDEA',title:'Meeting idea',filename:'idea.md',text:'Supplier call'},{id:'old',type:'VOICE',title:'Meeting audio',filename:'voice-old.m4a'}],before=structuredClone(items);assert.deepEqual(filterSavedItems(items,'ALL','meeting').map(x=>x.id),['new','middle','old']);assert.deepEqual(filterSavedItems(items,'TASK','meeting').map(x=>x.id),['new']);assert.deepEqual(filterSavedItems(items,'IDEA','meeting').map(x=>x.id),['middle']);assert.deepEqual(filterSavedItems(items,'VOICE','meeting').map(x=>x.id),['old']);assert.deepEqual(items,before)});
test('library search is accessible, debounced, local, safely rendered, and opens existing results',async()=>{const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8'),js=await readFile(new URL('../public/app.js',import.meta.url),'utf8'),search=await readFile(new URL('../public/search.js',import.meta.url),'utf8');assert.match(html,/for="savedSearch"/);assert.match(html,/placeholder="Search saved items…"/);assert.match(js,/setTimeout\(render,250\)/);assert.match(js,/No matching saved items\./);assert.match(js,/closest\('\[data-id\]'\).*openItem\(b\.dataset\.id\)/);assert.match(js,/escapeHtml\(x\.title\)/);assert.match(js,/escapeHtml\(x\.filename\)/);assert.doesNotMatch(search,/fetch|XMLHttpRequest|OpenAI/i)});
test('Home clears the saved-items search',async()=>{const js=await readFile(new URL('../public/app.js',import.meta.url),'utf8');assert.match(js,/function home\(\).*searchQuery='';\$\('#savedSearch'\)\.value=''/)});
test('photo sizing preserves aspect ratio and never enlarges small images',()=>{assert.deepEqual(photoSize(4032,3024),{width:1920,height:1440});assert.deepEqual(photoSize(800,600),{width:800,height:600});assert.deepEqual(photoSize(1000,2000),{width:960,height:1920})});
test('photo validation accepts passive iPhone formats and rejects active or non-image files',()=>{for(const type of ['image/jpeg','image/png','image/webp','image/heic','image/heif'])assert.equal(validPhoto({type}),true);for(const type of ['image/svg+xml','text/html','application/javascript',''])assert.equal(validPhoto({type}),false)});
test('photo filenames inherit note naming, support custom names, and keep stable numbering',()=>{const idea='[Idea-bathroom-layout] 26-Sep-14-01.md',task='[Task-call-dentist] 26-Sep-14-02.md';assert.equal(photoFilename(idea,1),'[Idea-bathroom-layout] 26-Sep-14-01-Photo-01.jpg');assert.equal(photoFilename(task,2),'[Task-call-dentist] 26-Sep-14-02-Photo-02.jpg');assert.equal(photoFilename('[Idea-xxx] 26-Sep-14-01.md',1),'[Idea-xxx] 26-Sep-14-01-Photo-01.jpg');assert.equal(photoFilename(idea,1,'bathroom-entrance'),'[Idea-bathroom-entrance] 26-Sep-14-01-Photo-01.jpg');assert.equal(nextPhotoNumber([{number:1},{number:3}]),4)});
test('only inherited photo names follow note renames',()=>{const photos=[{id:'a',number:1,inherited:true,filename:'old-1.jpg'},{id:'b',number:2,inherited:false,filename:'custom-2.jpg'}],renamed=inheritedPhotoNames(photos,'[Idea-new-name] 26-Sep-14-01.md');assert.equal(renamed[0].filename,'[Idea-new-name] 26-Sep-14-01-Photo-01.jpg');assert.equal(renamed[1].filename,'custom-2.jpg');assert.equal(photos[0].filename,'old-1.jpg')});
test('photo filenames search through the parent note and respect filters',()=>{const items=[{id:'idea',type:'IDEA',title:'Sketch',filename:'idea.md',text:'',attachments:[{filename:'[Idea-bathroom] 26-Sep-14-01-Photo-01.jpg'}]},{id:'task',type:'TASK',title:'Call',filename:'task.md',text:'',attachments:[{filename:'[Task-dentist] 26-Sep-14-02-Photo-01.jpg'}]}];assert.deepEqual(filterSavedItems(items,'ALL','bathroom').map(x=>x.id),['idea']);assert.deepEqual(filterSavedItems(items,'IDEA','photo-01').map(x=>x.id),['idea']);assert.deepEqual(filterSavedItems(items,'TASK','photo-01').map(x=>x.id),['task'])});
test('photo UI is local, accessible, failure-safe, and isolated from voice storage',async()=>{const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8'),js=await readFile(new URL('../public/app.js',import.meta.url),'utf8');assert.match(html,/id="photoInput"[^>]+accept="image\/jpeg,image\/png,image\/webp,image\/heic,image\/heif"/);assert.match(html,/id="addPhotoBtn"[^>]*>＋ Add Photo/);assert.match(html,/aria-labelledby="photoDialogName"/);assert.match(js,/indexedDB\.open\(DB,2\)/);assert.match(js,/createObjectStore\('photos'\)/);assert.match(js,/await putPhoto\(id,blob\)/);assert.match(js,/QuotaExceededError/);assert.match(js,/navigator\.storage\?\.persist/);assert.match(js,/URL\.revokeObjectURL/);assert.match(js,/else for\(const photo of current\.attachments/);assert.match(js,/current\.type==='VOICE'.*db\('delete',part\.id\).*else for/s);assert.doesNotMatch(js,/fetch\(|OpenAI/i);assert.doesNotMatch(html,/type="file"[^>]+capture=/)});
test('photo rendering and removal preserve note text and use safe DOM APIs',async()=>{const js=await readFile(new URL('../public/app.js',import.meta.url),'utf8');assert.match(js,/filename\.textContent=photo\.filename/);assert.match(js,/image\.alt=photo\.filename/);assert.match(js,/box\.replaceChildren\(\)/);assert.match(js,/current\.attachments=current\.attachments\.filter/);assert.match(js,/current\.text=\$\('#note'\)\.value/);assert.match(js,/current\.attachments\|\|=\[\]/);assert.match(js,/Enter a photo name/);assert.match(js,/replace\(\/\[\\\\\/:\*\?"<>\|\\\[\\\]\]\//)});
test('uses separate numbered filenames',async()=>{const js=await readFile(new URL('../public/app.js',import.meta.url),'utf8');assert.match(js,/Idea/);assert.match(js,/Task/);assert.match(js,/Voice/);assert.match(js,/padStart\(2,'0'\)/)});
test('View Photo reuses the loaded preview without Safari image decoding',async()=>{const js=await readFile(new URL('../public/app.js',import.meta.url),'utf8'),css=await readFile(new URL('../public/refinements.css',import.meta.url),'utf8');assert.match(js,/sourceUrl=target\.closest\('\.photo-card'\)\.querySelector\('img'\)\?\.src/);assert.match(js,/image\.src=sourceUrl;image\.alt=photo\.filename;\$\('#photoDialog'\)\.showModal\(\)/);assert.doesNotMatch(js,/image\.decode|dialogPhotoUrl/);assert.match(css,/\.photo-dialog img\{[^}]*width:100%;height:auto/)});
test('photos avoid WebKit persisted-Blob rendering failures and migrate earlier entries',async()=>{const js=await readFile(new URL('../public/app.js',import.meta.url),'utf8');assert.match(js,/putPhoto\(id,blob\).*blob\.arrayBuffer\(\)/s);assert.match(js,/stored instanceof Blob.*stored\.arrayBuffer\(\).*db\('put'/s);assert.match(js,/new Blob\(\[stored\.bytes\]/);assert.match(js,/blob=await getPhoto\(photo\.id\)/)});
test('is installable and offline capable',async()=>{const manifest=JSON.parse(await readFile(new URL('../public/manifest.webmanifest',import.meta.url),'utf8')),sw=await readFile(new URL('../public/service-worker.js',import.meta.url),'utf8');assert.equal(manifest.display,'standalone');assert.match(sw,/quiet-notes-iphone-v18/);assert.match(sw,/\/search\.js/);assert.match(sw,/\/photos\.js/)});
