import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { createServer } from '../server.js';
import { filterSavedItems, matchesSavedItem } from '../public/search.js';

function request(port, path='/') { return new Promise((resolve,reject)=>{const req=http.get({hostname:'127.0.0.1',port,path},res=>{let body='';res.on('data',x=>body+=x);res.on('end',()=>resolve({status:res.statusCode,body,headers:res.headers}))});req.on('error',reject)}) }

test('serves the iPhone app and health check',async()=>{const server=createServer();await new Promise(ok=>server.listen(0,'127.0.0.1',ok));try{const port=server.address().port,home=await request(port),health=await request(port,'/health');assert.equal(home.status,200);assert.match(home.body,/Private working copies/);assert.deepEqual(JSON.parse(health.body),{ok:true,version:12})}finally{await new Promise(ok=>server.close(ok))}});
test('has distinct idea, task, and voice capture',async()=>{const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8');assert.match(html,/New Idea/);assert.match(html,/New Task/);assert.match(html,/Voice Memo/);assert.match(html,/voiceCount/);assert.match(html,/Home/)});
test('stores locally, supports rename, and exports through the share sheet',async()=>{const js=await readFile(new URL('../public/app.js',import.meta.url),'utf8'),html=await readFile(new URL('../public/index.html',import.meta.url),'utf8');assert.match(js,/localStorage/);assert.match(js,/indexedDB/);assert.match(js,/navigator\.share/);assert.match(js,/renamedFile/);assert.match(js,/saveVoiceName/);assert.match(html,/Save\/Rename Voice Memo/);assert.doesNotMatch(js,/\/local\//)});
test('autosaves visible edits and exports the current copy',async()=>{const js=await readFile(new URL('../public/app.js',import.meta.url),'utf8'),html=await readFile(new URL('../public/index.html',import.meta.url),'utf8');assert.match(js,/function markDirty/);assert.match(js,/setTimeout\(\(\)=>saveNote\(true\),700\)/);assert.match(js,/function exportNote\(\)\{saveNote\(true\)/);assert.match(html,/Export Current Copy/);assert.doesNotMatch(html,/Draft protected/)});
test('voice memos append related recordings without overwriting',async()=>{const js=await readFile(new URL('../public/app.js',import.meta.url),'utf8'),html=await readFile(new URL('../public/index.html',import.meta.url),'utf8');assert.match(js,/recordings\.push/);assert.match(js,/Add Related Recording/);assert.match(js,/Part-/);assert.match(js,/migrateVoice/);assert.match(html,/voicePreview.*recordBtn/s);assert.doesNotMatch(js,/Record Again/)});
test('related recording action follows the recording cards without helper clutter',async()=>{const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8'),js=await readFile(new URL('../public/app.js',import.meta.url),'utf8');assert.match(html,/voicePreview.*recordBtn.*deleteVoiceThread/s);assert.doesNotMatch(html,/Enter a name before recording/);assert.doesNotMatch(js,/never replaces the recordings above/)});
test('search matches title, filename, text, and type with normalization and AND terms',()=>{const idea={type:'IDEA',title:'Noise Cancelling App',filename:'[Idea-noise] 26-Sep-14-01.md',text:'Public bathroom concept'};assert.equal(matchesSavedItem(idea,'NOISE'),true);assert.equal(matchesSavedItem(idea,'26-sep-14'),true);assert.equal(matchesSavedItem(idea,'bathroom'),true);assert.equal(matchesSavedItem(idea,'idea'),true);assert.equal(matchesSavedItem(idea,'  NOISE bathroom  '),true);assert.equal(matchesSavedItem(idea,'noise missing'),false);assert.equal(matchesSavedItem(idea,'   '),true);assert.equal(matchesSavedItem({type:'VOICE',title:'Anata Wa',filename:'[Voice-Anata-Wa] 26-Sep-14-01-Part-01.m4a'},'voice anata'),true)});
test('search combines with every category filter, preserves order, and does not mutate items',()=>{const items=[{id:'new',type:'TASK',title:'Meeting task',filename:'task-new.md',text:'Supplier call'},{id:'middle',type:'IDEA',title:'Meeting idea',filename:'idea.md',text:'Supplier call'},{id:'old',type:'VOICE',title:'Meeting audio',filename:'voice-old.m4a'}],before=structuredClone(items);assert.deepEqual(filterSavedItems(items,'ALL','meeting').map(x=>x.id),['new','middle','old']);assert.deepEqual(filterSavedItems(items,'TASK','meeting').map(x=>x.id),['new']);assert.deepEqual(filterSavedItems(items,'IDEA','meeting').map(x=>x.id),['middle']);assert.deepEqual(filterSavedItems(items,'VOICE','meeting').map(x=>x.id),['old']);assert.deepEqual(items,before)});
test('library search is accessible, debounced, local, safely rendered, and opens existing results',async()=>{const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8'),js=await readFile(new URL('../public/app.js',import.meta.url),'utf8'),search=await readFile(new URL('../public/search.js',import.meta.url),'utf8');assert.match(html,/for="savedSearch"/);assert.match(html,/placeholder="Search saved items…"/);assert.match(js,/setTimeout\(render,250\)/);assert.match(js,/No matching saved items\./);assert.match(js,/closest\('\[data-id\]'\).*openItem\(b\.dataset\.id\)/);assert.match(js,/escapeHtml\(x\.title\)/);assert.match(js,/escapeHtml\(x\.filename\)/);assert.doesNotMatch(search,/fetch|XMLHttpRequest|OpenAI/i)});
test('uses separate numbered filenames',async()=>{const js=await readFile(new URL('../public/app.js',import.meta.url),'utf8');assert.match(js,/Idea/);assert.match(js,/Task/);assert.match(js,/Voice/);assert.match(js,/padStart\(2,'0'\)/)});
test('is installable and offline capable',async()=>{const manifest=JSON.parse(await readFile(new URL('../public/manifest.webmanifest',import.meta.url),'utf8')),sw=await readFile(new URL('../public/service-worker.js',import.meta.url),'utf8');assert.equal(manifest.display,'standalone');assert.match(sw,/quiet-notes-iphone-v13/);assert.match(sw,/\/search\.js/)});
